-- Create user_daily_challenges table if it doesn't exist
create table if not exists public.user_daily_challenges (
    id uuid default gen_random_uuid() primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    date date not null default CURRENT_DATE,
    content jsonb not null, -- Stores the JSON challenge generated by AI
    completed boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- Ensure one challenge per user per day
    unique(user_id, date)
);

-- Enable RLS
alter table public.user_daily_challenges enable row level security;

-- Policies
-- Policies (Drop first to avoid errors)
drop policy if exists "Users can view their own challenges" on public.user_daily_challenges;
create policy "Users can view their own challenges"
    on public.user_daily_challenges for select
    using (auth.uid() = user_id);

drop policy if exists "Users can insert/update their own challenges" on public.user_daily_challenges;
create policy "Users can insert/update their own challenges"
    on public.user_daily_challenges for insert
    with check (auth.uid() = user_id);

drop policy if exists "Users can update their own challenges" on public.user_daily_challenges;
create policy "Users can update their own challenges"
    on public.user_daily_challenges for update
    using (auth.uid() = user_id);
